name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6.*,<=3.8.*
  - jupyter
  - gensim
  - numpy
  - pandas
  - nltk
  - scikit-learn
  - matplotlib
  - praw
  - altair
  - altair_saver
  - selenium
