name: nlp
channels:
  - defaults
dependencies:
  - python[version='>=3.6.*,<=3.8.*']
  - jupyter
  - nltk
  - pandas
  - conda-forge::praw
  - gensim
  - selenium
  - altair
  - conda-forge::altair_saver
  - matplotlib
  - scikit-learn
  - numpy
